image: "python:3.7"

before_script:
  - python3 --version
  - pip3 install -r requirements.txt

stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  tags: ["dev"]
  script:
  - flake8 --max-line-length=120 *.py
