stages:
  - Static Analysis

flake8:
  stage: Static Analysis
  image: 
    name: python:3.7
  tags: ["dev"]
  before_script:
  - python3 --version
  - pip install -r requirements.txt
  script:
  - flake8 --max-line-length=120 *.py
